# Generated by Django 4.0.4 on 2022-07-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=80)),
                ('ciudad', models.CharField(max_length=80)),
                ('aventura', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=2000)),
                ('operador', models.CharField(max_length=80)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Turismo')),
                ('salida', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
    ]
